<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.35" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
		<PackageReference Include="Serilog" Version="4.1.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Bookify.Domain\Bookify.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Abstractions\Clock\" />
		<Folder Include="Caching\" />
		<Folder Include="Users\GetLoggedInUser\" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Bookify.Application.UnitTests" />
	</ItemGroup>

</Project>
